// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oocyxllcnabcegnsinwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vY3l4bGxjbmFiY2VnbnNpbndvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNzc5NjksImV4cCI6MjA2NDY1Mzk2OX0.KF6BSy95I8P2kseGuKcedPrCIuWmvytWbp019jNg3KU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);