// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdumengvbndveepkponj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkdW1lbmd2Ym5kdmVlcGtwb25qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNTY5ODksImV4cCI6MjA2NzczMjk4OX0.poInFg3xiPNTi2prR9f7CAjtheWWdA_sbrSpJ-v8Fi8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});